CREATE TABLE cars (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      is_available BOOLEAN NOT NULL,
                      latitude FLOAT NOT NULL,
                      longitude FLOAT NOT NULL,
                      model VARCHAR(255) NOT NULL,
                      price_per_min NUMERIC(10,2) NOT NULL,
                      version BIGINT
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       balance NUMERIC(10,2) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       latitude FLOAT,
                       longitude FLOAT,
                       name VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL
);

CREATE TABLE rides (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       end_latitude FLOAT,
                       end_longitude FLOAT,
                       end_time TIMESTAMP(6),
                       start_latitude FLOAT NOT NULL,
                       start_longitude FLOAT NOT NULL,
                       start_time TIMESTAMP(6) NOT NULL,
                       total_cost NUMERIC(10,2),
                       car_id BIGINT NOT NULL,
                       user_id BIGINT NOT NULL,
                       CONSTRAINT fk_rides_car FOREIGN KEY (car_id) REFERENCES cars(id),
                       CONSTRAINT fk_rides_user FOREIGN KEY (user_id) REFERENCES users(id)
);